### ISSUE TITLE
Не активно поле "откуда"

### ISSUE THREAD

**Issue by UBCh** [UBCh/PageObject#1]
1.создать новый проект gradle
2. настроить Ci
3. в папку artifacts добавить app-ibank-build-for-testers.jar 
4. в терминале командой java -jar ./artifacts/app-ibank-build-for-testers.jar запустить app-ibank-build-for-testers.jar 
5. открыть "http://localhost:9999"
6. заполнить поля формы 
login: 'vasya' ,  password: 'qwerty123'
7. нажать кнопку "продолжить"
8. заполнить поле формы verification code (hardcoded): '12345'
9. нажать кнопку "продолжить"
10. нажать кнопку "пополнить"
11. заполнить поле формы  -сумма
12. заполнить поле формы "откуда"
13. заполнить поле формы "куда"

ожидаемый результат- в поле можно ввести номер кредитной карты
фактический результат - поле не активно.

![image](https://user-images.githubusercontent.com/89996798/147878858-461f5a99-ea23-409f-87e6-1a693f2b77d4.png)

окружение
УстройствоIRBIS-NB70, 
OC Windows 10, 
Яндекс.Браузер.Версия
21.6.3.756

**Comment by andrew-pahomov** [comment]
Указанное Вами поле не должно быть активным. Вы выбираете карту для пополнения на странице дашбоарда и поле заполняется автоматически.
